-- ============================================================================
-- Lozi — Cumulative-sales commission reduction system
-- Applied to project niloddwnllhsvrmuxfxw on 2026-06-28.
-- This file documents the live schema (idempotent). Two independent tracks per
-- seller (retail / wholesale); commission is stored on each order at completion
-- and never recomputed. Wallet money is NOT moved (record-on-order mode):
-- the order keeps the frozen snapshot and the seller counter is adjusted.
-- ============================================================================

-- ── 1. Tier reference table (editable from admin without code changes) ──────
create table if not exists public.commission_tiers (
  id         bigint generated by default as identity primary key,
  segment    text not null check (segment in ('retail','wholesale')),
  level      int  not null check (level between 1 and 7),
  min_sales  numeric(14,2) not null,
  max_sales  numeric(14,2),            -- NULL = infinity (top tier)
  rate       numeric(6,4) not null,    -- fraction, 1.50% = 0.0150
  unique (segment, level)
);
alter table public.commission_tiers enable row level security;
drop policy if exists commission_tiers_read on public.commission_tiers;
create policy commission_tiers_read on public.commission_tiers for select using (true);
drop policy if exists commission_tiers_admin on public.commission_tiers;
create policy commission_tiers_admin on public.commission_tiers for all
  using (public.is_admin()) with check (public.is_admin());

insert into public.commission_tiers (segment, level, min_sales, max_sales, rate) values
  ('retail',1,0,9999,0.0200),('retail',2,10000,49999,0.0175),('retail',3,50000,99999,0.0150),
  ('retail',4,100000,499999,0.0125),('retail',5,500000,999999,0.0100),('retail',6,1000000,4999999,0.0075),
  ('retail',7,5000000,null,0.0050),
  ('wholesale',1,0,99999,0.0070),('wholesale',2,100000,499999,0.0060),('wholesale',3,500000,999999,0.0050),
  ('wholesale',4,1000000,4999999,0.0040),('wholesale',5,5000000,9999999,0.0030),('wholesale',6,10000000,49999999,0.0020),
  ('wholesale',7,50000000,null,0.0010)
on conflict (segment, level) do update
  set min_sales = excluded.min_sales, max_sales = excluded.max_sales, rate = excluded.rate;

-- ── 2. Per-seller lifetime counters + order commission snapshot ─────────────
alter table public.profiles
  add column if not exists retail_cumulative_sales    numeric(14,2) not null default 0,
  add column if not exists wholesale_cumulative_sales numeric(14,2) not null default 0;

alter table public.orders
  add column if not exists segment                 text check (segment in ('retail','wholesale')),
  add column if not exists goods_subtotal          numeric(14,2),
  add column if not exists commission_rate_applied numeric(6,4),
  add column if not exists commission_amount       numeric(14,2),
  add column if not exists cumulative_before        numeric(14,2),
  add column if not exists commission_state         text check (commission_state in ('charged','reversed','partially_reversed')),
  add column if not exists reversed_amount          numeric(14,2) not null default 0;

-- ── 3. Read-only tier lookup (single source of truth for level/rate) ────────
create or replace function public.get_tier(p_segment text, p_cumulative numeric)
returns table(level int, rate numeric, min_sales numeric, max_sales numeric)
language sql stable set search_path = public as $$
  select t.level, t.rate, t.min_sales, t.max_sales
  from public.commission_tiers t
  where t.segment = p_segment
    and p_cumulative >= t.min_sales
    and (t.max_sales is null or p_cumulative <= t.max_sales)
  order by t.level limit 1;
$$;
grant execute on function public.get_tier(text, numeric) to anon, authenticated;

-- Classify an order: product.market_segment, else seller role, else retail.
create or replace function public.resolve_order_segment(p_items jsonb, p_seller uuid)
returns text language plpgsql stable set search_path = public as $$
declare v_seg text; v_role text;
begin
  select p.market_segment into v_seg
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) it
  join public.products p on p.id = (it->>'p')::uuid
  where p.market_segment in ('retail','wholesale') limit 1;
  if v_seg is not null then return v_seg; end if;
  select role into v_role from public.profiles where user_id = p_seller;
  if coalesce(v_role,'') ilike '%wholesale%' then return 'wholesale'; end if;
  return 'retail';
exception when others then return 'retail';
end;
$$;

-- ── 4. Charge at completion (atomic, idempotent; rate from cumulative_before)─
create or replace function public.charge_commission(p_order_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare o public.orders%rowtype; v_seg text; v_goods numeric(14,2);
        v_c numeric(14,2); v_rate numeric(6,4); v_comm numeric(14,2);
begin
  select * into o from public.orders where id = p_order_id for update;
  if not found then return; end if;
  if o.commission_state is not null then return; end if;
  v_seg   := coalesce(o.segment, public.resolve_order_segment(o.items, o.seller_vendor_id));
  v_goods := coalesce(o.goods_subtotal, coalesce(o.total,0) - coalesce(o.delivery_fee,0));
  if v_goods < 0 then v_goods := 0; end if;
  perform 1 from public.profiles where user_id = o.seller_vendor_id for update;
  if v_seg = 'wholesale' then
    select coalesce(wholesale_cumulative_sales,0) into v_c from public.profiles where user_id = o.seller_vendor_id;
  else
    select coalesce(retail_cumulative_sales,0)    into v_c from public.profiles where user_id = o.seller_vendor_id;
  end if;
  v_c := coalesce(v_c, 0);
  select t.rate into v_rate from public.get_tier(v_seg, v_c) t;
  v_rate := coalesce(v_rate, 0);
  v_comm := round(v_goods * v_rate, 2);
  update public.orders set segment=v_seg, goods_subtotal=v_goods, commission_rate_applied=v_rate,
    commission_amount=v_comm, cumulative_before=v_c, commission_state='charged', reversed_amount=0
  where id = p_order_id;
  if v_seg = 'wholesale' then
    update public.profiles set wholesale_cumulative_sales = coalesce(wholesale_cumulative_sales,0) + v_goods where user_id = o.seller_vendor_id;
  else
    update public.profiles set retail_cumulative_sales    = coalesce(retail_cumulative_sales,0)    + v_goods where user_id = o.seller_vendor_id;
  end if;
end;
$$;
revoke all on function public.charge_commission(uuid) from public, anon, authenticated;

-- ── 5. Reverse full (NULL) or partial; zero floor + double-reverse guard ────
create or replace function public.reverse_commission(p_order_id uuid, p_returned_goods numeric default null)
returns void language plpgsql security definer set search_path = public as $$
declare o public.orders%rowtype; v_ret_goods numeric(14,2); v_already_g numeric(14,2);
        v_max_more numeric(14,2); v_refund numeric(14,2); v_new_rev numeric(14,2); v_new_state text;
begin
  select * into o from public.orders where id = p_order_id for update;
  if not found then return; end if;
  if o.commission_state is null or o.commission_state = 'reversed' then return; end if;
  if coalesce(o.goods_subtotal,0) <= 0 then return; end if;
  v_already_g := round(o.goods_subtotal * (coalesce(o.reversed_amount,0) / nullif(o.commission_amount,0)), 2);
  v_max_more  := greatest(o.goods_subtotal - coalesce(v_already_g,0), 0);
  if p_returned_goods is null then v_ret_goods := v_max_more;
  else v_ret_goods := least(greatest(p_returned_goods,0), v_max_more); end if;
  if v_ret_goods <= 0 then return; end if;
  v_refund  := round(o.commission_amount * (v_ret_goods / o.goods_subtotal), 2);
  v_new_rev := round(coalesce(o.reversed_amount,0) + v_refund, 2);
  if v_new_rev > o.commission_amount then v_new_rev := o.commission_amount; end if;
  if (v_already_g + v_ret_goods) >= o.goods_subtotal then v_new_state := 'reversed'; v_new_rev := o.commission_amount;
  else v_new_state := 'partially_reversed'; end if;
  perform 1 from public.profiles where user_id = o.seller_vendor_id for update;
  update public.orders set reversed_amount = v_new_rev, commission_state = v_new_state where id = p_order_id;
  if o.segment = 'wholesale' then
    update public.profiles set wholesale_cumulative_sales = greatest(coalesce(wholesale_cumulative_sales,0) - v_ret_goods, 0) where user_id = o.seller_vendor_id;
  else
    update public.profiles set retail_cumulative_sales = greatest(coalesce(retail_cumulative_sales,0) - v_ret_goods, 0) where user_id = o.seller_vendor_id;
  end if;
end;
$$;
revoke all on function public.reverse_commission(uuid, numeric) from public, anon, authenticated;

-- Admin-guarded manual reversal entry point (dashboard partial/full returns).
create or replace function public.admin_reverse_commission(p_order_id uuid, p_returned_goods numeric default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  perform public.reverse_commission(p_order_id, p_returned_goods);
end;
$$;
revoke all on function public.admin_reverse_commission(uuid, numeric) from public, anon;
grant execute on function public.admin_reverse_commission(uuid, numeric) to authenticated;

-- ── 6. Lifecycle triggers: charge on delivered, reverse on cancel/return ────
create or replace function public.orders_commission_sync()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if NEW.status = 'delivered' and coalesce(OLD.status,'') is distinct from 'delivered'
     and NEW.commission_state is null then
    perform public.charge_commission(NEW.id);
  end if;
  if NEW.status in ('cancelled','rejected','returned')
     and coalesce(OLD.status,'') not in ('cancelled','rejected','returned')
     and NEW.commission_state = 'charged' then
    perform public.reverse_commission(NEW.id, null);
  end if;
  return NEW;
end;
$$;
revoke all on function public.orders_commission_sync() from public, anon, authenticated;
drop trigger if exists trg_orders_commission_sync on public.orders;
create trigger trg_orders_commission_sync after update of status on public.orders
  for each row execute function public.orders_commission_sync();

create or replace function public.orders_commission_sync_ins()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if NEW.status = 'delivered' and NEW.commission_state is null then
    perform public.charge_commission(NEW.id);
  end if;
  return NEW;
end;
$$;
revoke all on function public.orders_commission_sync_ins() from public, anon, authenticated;
drop trigger if exists trg_orders_commission_sync_ins on public.orders;
create trigger trg_orders_commission_sync_ins after insert on public.orders
  for each row execute function public.orders_commission_sync_ins();

-- ── 7. Backfill already-delivered orders in chronological order ─────────────
do $$
declare r record;
begin
  for r in select id from public.orders where status='delivered' and commission_state is null order by created_at asc loop
    perform public.charge_commission(r.id);
  end loop;
end $$;
